# Generated by Django 5.2.15 on 2026-06-25 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SandboxSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "container_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("container_name", models.CharField(max_length=128, unique=True)),
                ("workspace_path", models.CharField(max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "创建中"),
                            ("running", "运行中"),
                            ("idle", "空闲"),
                            ("stopped", "已停止"),
                            ("destroyed", "已销毁"),
                            ("error", "错误"),
                        ],
                        default="creating",
                        max_length=20,
                    ),
                ),
                ("cpu_limit", models.FloatField(default=1.0)),
                ("memory_limit_mb", models.IntegerField(default=512)),
                ("max_lifetime_minutes", models.IntegerField(default=1440)),
                ("idle_timeout_minutes", models.IntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                ("destroyed_at", models.DateTimeField(blank=True, null=True)),
                ("active_conversations", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sandbox_sessions",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="sandbox_ses_user_id_02c1cd_idx"
                    ),
                    models.Index(
                        fields=["status", "last_active_at"],
                        name="sandbox_ses_status_61bbd7_idx",
                    ),
                ],
            },
        ),
    ]
