# Generated by Django 5.2.15 on 2026-06-18 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapabilityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=64, unique=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "能力标签",
                "verbose_name_plural": "能力标签",
                "db_table": "capability_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128)),
                (
                    "feishu_app_id",
                    models.CharField(
                        help_text="飞书应用 App ID", max_length=128, unique=True
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Agent 回调 webhook",
                        max_length=512,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "离线"),
                            ("busy", "忙碌"),
                            ("error", "异常"),
                        ],
                        db_index=True,
                        default="offline",
                        max_length=16,
                    ),
                ),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                (
                    "secret_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="HMAC-SHA256 签名密钥（Agent 注册时自动生成）",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("version", models.CharField(blank=True, default="", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capabilities",
                    models.ManyToManyField(
                        blank=True, related_name="agents", to="agents.capabilitytag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agent",
                "db_table": "agents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128)),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("version", models.CharField(default="1.0.0", max_length=32)),
                ("description", models.TextField(blank=True, default="")),
                ("file_url", models.URLField(blank=True, default="", max_length=512)),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, default="", help_text="SHA256 校验值", max_length=64
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, help_text="字节数"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("meyo", "Meyo 社区"),
                            ("local", "本地开发"),
                            ("third_party", "第三方"),
                        ],
                        default="local",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "启用"),
                            ("deprecated", "已弃用"),
                            ("draft", "草稿"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("category", models.CharField(blank=True, default="", max_length=64)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "meyo_skill_id",
                    models.CharField(
                        blank=True, default="", max_length=64, null=True, unique=True
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "技能",
                "verbose_name_plural": "技能",
                "db_table": "skill_registry",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "category"],
                        name="skill_regis_status_4166dc_idx",
                    ),
                    models.Index(
                        fields=["source"], name="skill_regis_source_3776fa_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_assignments",
                        to="agents.agent",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skill_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_assignments",
                        to="agents.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 技能分配",
                "verbose_name_plural": "Agent 技能分配",
                "db_table": "agent_skill_assignments",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "contract",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="SPEC 契约：定义 Agent 间通信的 API 路径、数据模型、共享常量",
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "knowledge_refs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="引用的 knowledge_entries ID 列表",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待分配"),
                            ("assigned", "已分配"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "紧急"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="agents.agent",
                    ),
                ),
                (
                    "assigned_skills",
                    models.ManyToManyField(
                        blank=True, related_name="tasks", to="agents.skill"
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="父任务（依赖链）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtasks",
                        to="agents.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "db_table": "tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=256)),
                ("content", models.TextField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("solution", "解决方案"),
                            ("pitfall", "踩坑记录"),
                            ("best_practice", "最佳实践"),
                            ("snippet", "代码片段"),
                            ("lesson", "经验教训"),
                        ],
                        db_index=True,
                        default="solution",
                        max_length=32,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "所有 Agent 可见"),
                            ("team", "同团队可见"),
                            ("private", "仅当前 Agent"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=16,
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("useful_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_entries",
                        to="agents.agent",
                    ),
                ),
                (
                    "related_skills",
                    models.ManyToManyField(
                        blank=True, related_name="knowledge_entries", to="agents.skill"
                    ),
                ),
                (
                    "source_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_entries",
                        to="agents.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识条目",
                "verbose_name_plural": "知识条目",
                "db_table": "knowledge_entries",
                "ordering": ["-relevance_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("warning", "警告"),
                            ("error", "错误"),
                            ("debug", "调试"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "quality_gate",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{complexity, security, null_safety, design_consistency, health_score}",
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_logs",
                        to="agents.agent",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="agents.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "执行日志",
                "verbose_name_plural": "执行日志",
                "db_table": "execution_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["status", "last_heartbeat"], name="agents_status_2a3209_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentskill",
            index=models.Index(
                fields=["agent", "is_active"], name="agent_skill_agent_i_3417fb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentskill",
            unique_together={("agent", "skill")},
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "priority"], name="tasks_status_0fbdac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["agent", "status"], name="tasks_agent_i_8449fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["created_at"], name="tasks_created_db4e37_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgeentry",
            index=models.Index(
                fields=["entry_type", "visibility"],
                name="knowledge_e_entry_t_ce194f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeentry",
            index=models.Index(
                fields=["relevance_score"], name="knowledge_e_relevan_e328d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionlog",
            index=models.Index(
                fields=["task", "created_at"], name="execution_l_task_id_8fb195_idx"
            ),
        ),
    ]
