# Generated by Django 5.2.15 on 2026-06-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="content",
            field=models.TextField(
                blank=True, default="", help_text="SKILL.md 原始 Markdown 内容"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="meyo_skill_id",
            field=models.CharField(
                blank=True, default=None, max_length=64, null=True, unique=True
            ),
        ),
    ]
