# Generated by Django 5.2.15 on 2026-06-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_add_skill_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="config_encrypted",
            field=models.TextField(
                blank=True,
                default="",
                help_text="AES 加密后的配置 JSON（含 API Key 等敏感信息）",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="config_public",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="公开配置：端口、域名、模型等非敏感信息",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="portrait",
            field=models.TextField(
                blank=True, default="", help_text="人物画像：性格、特长、角色定位"
            ),
        ),
    ]
