# Generated by Django 5.2.15 on 2026-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_add_agent_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="CronExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(db_index=True, max_length=32)),
                ("name", models.CharField(db_index=True, max_length=128)),
                ("skill", models.CharField(blank=True, default="", max_length=64)),
                ("schedule", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("ok", "成功"),
                            ("error", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "定时任务执行",
                "verbose_name_plural": "定时任务执行",
                "db_table": "cron_executions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job_id", "-created_at"],
                        name="cron_execut_job_id_a8b5c0_idx",
                    ),
                    models.Index(
                        fields=["status"], name="cron_execut_status_75a146_idx"
                    ),
                ],
            },
        ),
    ]
