# Generated by Django 5.2.15 on 2026-06-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_cronexecution"),
    ]

    operations = [
        migrations.AddField(
            model_name="cronexecution",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cron_executions",
                to="agents.agent",
            ),
        ),
    ]
