# Generated by Django 5.2.15 on 2026-06-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_cronexecution_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="cronexecution",
            name="source",
            field=models.CharField(
                choices=[
                    ("user", "用户派发"),
                    ("cron", "定时触发"),
                    ("agent", "Agent自发"),
                ],
                db_index=True,
                default="cron",
                max_length=16,
            ),
        ),
    ]
