# Generated by Django 5.2.15 on 2026-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0008_add_conversation_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待分配"),
                    ("assigned", "已分配"),
                    ("in_progress", "执行中"),
                    ("running", "执行中(旧)"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                    ("cancelled", "已取消"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
