# Generated by Django 5.2.15 on 2026-06-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0009_add_in_progress_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="processed",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Hermes 是否已处理"
            ),
        ),
    ]
