# Generated by Django 5.2.15 on 2026-06-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0010_add_message_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="feishu_chat_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="飞书会话ID，用于跨平台对话关联",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="source",
            field=models.CharField(
                choices=[("feishu", "飞书"), ("web", "Web")],
                db_index=True,
                default="web",
                help_text="消息来源",
                max_length=16,
            ),
        ),
    ]
