# Generated by Django 5.2.15 on 2026-06-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0011_add_source_feishu_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="source",
            field=models.CharField(
                choices=[
                    ("user", "用户派发"),
                    ("cron", "定时触发"),
                    ("agent", "Agent自发"),
                    ("web", "Web Chat"),
                    ("feishu", "飞书"),
                ],
                db_index=True,
                default="user",
                max_length=16,
            ),
        ),
    ]
