# Generated by Django 5.2.15 on 2026-06-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0012_add_task_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="富文本HTML、附件信息等元数据"
            ),
        ),
    ]
