# Generated by Django 5.2.15 on 2026-06-23 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0013_add_message_metadata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "消息", "verbose_name_plural": "消息"},
        ),
        migrations.CreateModel(
            name="ParentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField(help_text="用户原始消息")),
                (
                    "source",
                    models.CharField(
                        choices=[("feishu", "飞书"), ("web", "Web")],
                        default="web",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待云枢分析"),
                            ("PLANNING", "云枢拆解中"),
                            ("DISPATCHED", "子任务执行中"),
                            ("EVALUATING", "云枢评估中"),
                            ("REPLY", "已回复"),
                            ("FAILED", "失败"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "dispatch_plan",
                    models.JSONField(blank=True, help_text="云枢调度计划", null=True),
                ),
                ("final_reply", models.TextField(blank=True, null=True)),
                (
                    "yunshu_context",
                    models.JSONField(
                        blank=True, default=list, help_text="云枢历次评估上下文"
                    ),
                ),
                ("yunshu_call_count", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_tasks",
                        to="agents.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "parent_tasks",
            },
        ),
        migrations.CreateModel(
            name="ChildTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(help_text="banni | basir", max_length=32),
                ),
                (
                    "agent_profile",
                    models.CharField(help_text="Hermes profile name", max_length=64),
                ),
                ("task_prompt", models.TextField(help_text="子任务描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待启动"),
                            ("RUNNING", "执行中"),
                            ("DONE", "完成"),
                            ("FAILED", "失败"),
                            ("TIMED_OUT", "超时"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "pid",
                    models.IntegerField(blank=True, help_text="系统进程ID", null=True),
                ),
                (
                    "hermes_session_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("result", models.TextField(blank=True, null=True)),
                ("error_info", models.JSONField(blank=True, null=True)),
                (
                    "heartbeat_at",
                    models.DateTimeField(
                        blank=True, help_text="最后心跳时间", null=True
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="agents.parenttask",
                    ),
                ),
            ],
            options={
                "db_table": "child_tasks",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="parenttask",
            index=models.Index(
                fields=["status", "created_at"], name="parent_task_status_a6d545_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="childtask",
            index=models.Index(
                fields=["parent", "status"], name="child_tasks_parent__f17e82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="childtask",
            index=models.Index(
                fields=["heartbeat_at"], name="child_tasks_heartbe_ad75e2_idx"
            ),
        ),
    ]
