# Generated by Django 5.2.15 on 2026-06-23 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0014_add_parent_child_tasks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="childtask",
            options={},
        ),
        migrations.CreateModel(
            name="ProgressEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("heartbeat", "心跳"),
                            ("stage_mark", "阶段标记"),
                            ("partial_out", "部分输出"),
                            ("tool_call", "工具调用"),
                            ("error", "错误"),
                            ("done_signal", "完成信号"),
                        ],
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField(default=dict, help_text="事件载荷")),
                ("seq", models.IntegerField(default=0, help_text="事件序号")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_events",
                        to="agents.childtask",
                    ),
                ),
            ],
            options={
                "db_table": "progress_events",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["child_task", "seq"],
                        name="progress_ev_child_t_55b9e9_idx",
                    ),
                    models.Index(
                        fields=["child_task", "created_at"],
                        name="progress_ev_child_t_d12160_idx",
                    ),
                ],
            },
        ),
    ]
