# Generated by Django 5.2.15 on 2026-06-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0015_add_progress_event"),
    ]

    operations = []
