# Generated by Django 5.2.15 on 2026-06-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0016_add_fallback_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="childtask",
            name="completed_at",
            field=models.FloatField(
                blank=True, help_text="子任务完成时间戳", null=True
            ),
        ),
        migrations.AddField(
            model_name="childtask",
            name="dependencies",
            field=models.JSONField(
                blank=True, help_text="依赖的其他子任务ID列表", null=True
            ),
        ),
        migrations.AddField(
            model_name="childtask",
            name="is_correction",
            field=models.BooleanField(
                default=False, help_text="是否为 REFLECT FAIL 后的修正轮次"
            ),
        ),
        migrations.AddField(
            model_name="childtask",
            name="source_marker",
            field=models.CharField(
                blank=True,
                help_text="来源标记，如 task_1 (Banni)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="childtask",
            name="tokens_used",
            field=models.IntegerField(
                blank=True, help_text="消耗的 token 数（估算）", null=True
            ),
        ),
        migrations.CreateModel(
            name="Checkpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("PLAN_COMPLETED", "规划完成"),
                            ("EXECUTING", "执行中"),
                            ("REFLECT_PASSED", "反思通过"),
                            ("CORRECTING", "修正中"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "children_state",
                    models.JSONField(
                        default=dict,
                        help_text="{task_id: {status, result_ref}} 格式的子任务状态快照",
                    ),
                ),
                (
                    "yunshu_output_line",
                    models.IntegerField(
                        default=0, help_text="Yunshu stdout 最后读取行号"
                    ),
                ),
                (
                    "summary_text",
                    models.TextField(
                        blank=True,
                        help_text="恢复时喂给 Yunshu 的上下文摘要",
                        null=True,
                    ),
                ),
                ("is_latest", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="agents.parenttask",
                    ),
                ),
            ],
            options={
                "db_table": "checkpoints",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["parent_task", "-created_at"],
                        name="checkpoints_parent__01f639_idx",
                    )
                ],
            },
        ),
    ]
