# Generated by Django 5.2.15 on 2026-06-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0017_v4_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="output_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="输出面板内容（Agent 推送的文档/报告）",
            ),
        ),
    ]
