# Generated by Django 5.2.15 on 2026-06-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_output_panel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, help_text='节点标识，如 t1/t2', max_length=32)),
                ('label', models.CharField(help_text='节点名称', max_length=128)),
                ('description', models.TextField(blank=True, default='', help_text='节点描述')),
                ('agent_name', models.CharField(blank=True, default='', help_text='执行的 Agent 名称', max_length=64)),
                ('action', models.CharField(blank=True, default='', help_text='terminal | search | reason | write_file', max_length=32)),
                ('depends_on', models.JSONField(blank=True, default=list, help_text='依赖的 node_id 列表')),
                ('status', models.CharField(choices=[('pending', '等待'), ('running', '执行中'), ('done', '完成'), ('failed', '失败'), ('skipped', '跳过'), ('timed_out', '超时')], db_index=True, default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='执行耗时（毫秒）')),
                ('is_bottleneck', models.BooleanField(db_index=True, default=False, help_text='是否为性能卡点')),
                ('bottleneck_reason', models.CharField(blank=True, default='', help_text='卡点原因说明', max_length=256)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('seq', models.IntegerField(default=0, help_text='排序序号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_nodes', to='agents.childtask')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_nodes', to='agents.parenttask')),
            ],
            options={
                'verbose_name': '任务节点',
                'verbose_name_plural': '任务节点',
                'db_table': 'task_nodes',
                'ordering': ['parent_task', 'seq'],
                'indexes': [models.Index(fields=['parent_task', 'status'], name='task_nodes_parent__e464ea_idx'), models.Index(fields=['parent_task', 'seq'], name='task_nodes_parent__cc9e9e_idx')],
            },
        ),
    ]
