# Generated by Django 5.2.15 on 2026-06-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0019_add_tasknode"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="description_zh",
            field=models.TextField(blank=True, default="", help_text="中文说明"),
        ),
        migrations.AddField(
            model_name="skill",
            name="name_zh",
            field=models.CharField(
                blank=True, default="", help_text="中文名称", max_length=128
            ),
        ),
    ]
