# Generated by Django 5.2.15 on 2026-06-25 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0020_skill_zh"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Web 用户，用于权限控制",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
