# Generated by Django 5.2.15 on 2026-06-25 14:30

import agents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0022_password_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=256, upload_to=agents.models._upload_to
                    ),
                ),
                ("original_name", models.CharField(max_length=256)),
                (
                    "mime_type",
                    models.CharField(
                        default="application/octet-stream", max_length=128
                    ),
                ),
                ("size", models.BigIntegerField(default=0, help_text="字节数")),
                (
                    "is_admin",
                    models.BooleanField(
                        db_index=True, default=False, help_text="管理员文件不自动删除"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, help_text="沙箱过期时间", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploads",
                        to="agents.conversation",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "uploaded_files",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["uploader", "-created_at"],
                        name="uploaded_fi_uploade_174071_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="uploaded_fi_expires_8df13c_idx"
                    ),
                ],
            },
        ),
    ]
