# Generated by Django 5.2.15 on 2026-06-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0023_file_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="agent_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="关联Agent名，同Agent共享文件",
                max_length=128,
            ),
        ),
    ]
