# Generated by Django 5.2.15 on 2026-06-25 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0024_file_agent_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                help_text="关联的会话，Web Chat 消息自动创建",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="agents.conversation",
            ),
        ),
    ]
